"use client";

import { useMemo } from "react";

import { workoutPlannerDefaults } from "@/lib/constants";
import { canUseFeature, premiumFeatures } from "@/lib/premium";
import { useSupabaseSession } from "@/lib/supabase/use-supabase-session";
import { useUserProfile } from "@/hooks/use-user-profile";

import { PremiumPaywall } from "@/components/premium-paywall";
import { MacroCalculatorForm } from "./macro-calculator-panel/macro-calculator-form";
import { MacroPlanSection } from "./macro-calculator-panel/macro-plan-section";
import { MacroResultSection } from "./macro-calculator-panel/macro-result-section";
import { useMacroCalculatorPanel } from "./macro-calculator-panel/use-macro-calculator-panel";

export function MacroCalculatorPanel() {
  const { supabase, signedIn, tier } = useSupabaseSession() as { supabase: ReturnType<typeof useSupabaseSession>["supabase"]; signedIn: boolean; tier?: string | null };
  const { profile, loading: profileLoading } = useUserProfile();
  const controller = useMacroCalculatorPanel({ signedIn, supabase, userProfile: profile, profileLoading });
  const inputClass = "w-full rounded-xl border border-border bg-background px-4 py-3 text-foreground outline-none transition focus:border-primary";
  const canSaveHistory = canUseFeature(tier as any, "monthlyAnalytics") || canUseFeature(tier as any, "exportData") || canUseFeature(tier as any, "cloudBackup");

  const mealPlannerHref = useMemo(() => {
    if (!controller.result) {
      return "/meal";
    }

    const params = new URLSearchParams({
      calories: String(controller.result.calories),
      proteinGrams: String(controller.result.proteinGrams),
      carbsGrams: String(controller.result.carbsGrams),
      fatGrams: String(controller.result.fatGrams),
      goal: controller.form.goal
    });

    return `/meal?${params.toString()}`;
  }, [controller.form.goal, controller.result]);

  const workoutPlannerHref = useMemo(() => {
    const params = new URLSearchParams({
      goal: controller.form.goal,
      daysPerWeek: workoutPlannerDefaults.daysPerWeek,
      equipment: workoutPlannerDefaults.equipment
    });
    return `/workout?${params.toString()}`;
  }, [controller.form.goal]);

  return (
    <main className="min-h-screen bg-background text-foreground">
      <section className="mx-auto w-full max-w-5xl px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
        <div className="rounded-[2rem] border border-border bg-card p-5 shadow-soft sm:p-6">
          <p className="text-xs font-semibold uppercase tracking-[0.24em] text-primary">Macro calculator</p>
          <h1 className="mt-2 text-2xl font-semibold text-card-foreground sm:text-3xl">Calculate your targets from body composition</h1>
          <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">
            Results are generated by the backend and can be sent directly to the meal planner.
          </p>

          {!canSaveHistory ? (
            <PremiumPaywall
              title="Unlock saved history and advanced macro tools"
              description="Upgrade to save more macro plans, keep long-term history, and sync across devices."
              ctaHref="/signup"
              ctaLabel="Upgrade to Premium"
              secondaryHref="/dashboard"
              secondaryLabel="Maybe later"
            />
          ) : null}

          <MacroCalculatorForm
            form={controller.form}
            inputClass={inputClass}
            loading={controller.loading}
            onSubmit={controller.handleSubmit}
            onFieldChange={controller.setField}
            mealPlannerHref={mealPlannerHref}
            workoutPlannerHref={workoutPlannerHref}
            onCreateCustomTarget={controller.handleCreateCustomTarget}
          />

          <MacroPlanSection
            historyError={controller.historyError}
            editableMacro={controller.editableMacro}
            result={controller.result}
            planName={controller.planName}
            planId={controller.planId}
            planVersions={controller.planVersions}
            isEditing={controller.isEditing}
            savingPlan={controller.savingPlan}
            historyLoading={controller.historyLoading}
            onPlanNameChange={controller.setPlanName}
            onCustomizeTarget={controller.handleCustomizeTarget}
            onDoneEditing={() => controller.setEditing(false)}
            onSavePlan={controller.handleSavePlan}
            onLoadHistory={controller.handleLoadHistory}
            onUpdateMacro={controller.updateEditableMacro}
            inputClass={inputClass}
          />

          <MacroResultSection error={controller.error} signedIn={signedIn} planLoading={controller.planLoading} />
        </div>
      </section>
    </main>
  );
}
