import type { Language } from "@/lib/i18n";

export const strings = {
  nav: {
    brand: { vi: "FitBudget", en: "FitBudget" },
    dashboard: { vi: "Tổng quan", en: "Dashboard" },
    macro: { vi: "Macro", en: "Macro" },
    meal: { vi: "Meal", en: "Meal" },
    workout: { vi: "Workout", en: "Workout" },
    progress: { vi: "Tiến độ", en: "Progress" },
    login: { vi: "Đăng nhập", en: "Login" },
    signup: { vi: "Đăng ký", en: "Sign up" },
    logout: { vi: "Đăng xuất", en: "Logout" }
  },
  dashboard: {
    eyebrow: { vi: "Bảng điều khiển", en: "Dashboard" },
    heroTitle: { vi: "Gym + ăn + track - all in one", en: "Gym + eat + track - all in one" },
    heroDescription: {
      vi: "Tính macro cho body của m → sinh meal plan → log cân → lặp lại. EZ.",
      en: "Calc macros → build meal plan → log weight → repeat. EZ."
    },
    sessionLabel: { vi: "Phiên", en: "Session" },
    sessionChecking: { vi: "Đang kiểm tra...", en: "Checking..." },
    sessionSignedIn: { vi: "Đã đăng nhập", en: "Signed in" },
    sessionGuest: { vi: "Xem thử với tư cách khách", en: "Guest preview" },
    progressPreview: { vi: "Xem tiến độ", en: "Progress preview" },
    progressDesc: {
      vi: "Xu hướng cân nặng mới nhất từ Supabase khi bạn đăng nhập.",
      en: "Latest weight trend pulled from Supabase when you are signed in."
    },
    openTracker: { vi: "Mở tracker", en: "Open tracker" },
    loadingProgress: { vi: "Đang load... chờ xíu ⏳", en: "Loading... hang tight ⏳" },
    noEntries: { vi: "Chưa có data gì cả 🌱", en: "No data yet 🌱" },
    noEntriesDesc: { vi: "Log lần cân đầu tiên để bắt đầu chart.", en: "Drop your first weight check-in to start the chart." },
    addEntry: { vi: "Thêm dữ liệu", en: "Add entry" },
    nextSteps: { vi: "Bước tiếp theo", en: "Next steps" },
    calculateMacros: { vi: "Tính macro", en: "Calculate macros" },
    generateMealPlan: { vi: "Tạo meal plan", en: "Generate meal plan" },
    planWorkouts: { vi: "Lập lịch tập", en: "Plan workouts" },
    trackProgress: { vi: "Theo dõi tiến độ", en: "Track progress" }
  },
  theme: {
    sectionEyebrow: { vi: "Giao diện", en: "Appearance" },
    sectionTitle: { vi: "Chọn theme", en: "Choose theme" },
    currentPrefix: { vi: "Đang dùng", en: "Current" },
    loading: { vi: "Đang tải tuỳ chọn theme...", en: "Loading theme options..." },
    pickerLabel: { vi: "Chọn theme", en: "Pick a theme" }
  },
  auth: {
    welcomeBack: { vi: "Welcome back", en: "Welcome back" },
    createAccount: { vi: "Join the squad", en: "Join the squad" },
    loginTitle: { vi: "Đăng nhập FitBudget", en: "Log in to FitBudget" },
    signupTitle: { vi: "Tạo tài khoản FitBudget", en: "Create your FitBudget account" },
    loginDesc: { vi: "Vào meal plan, tiến độ và macro của m.", en: "Get into your meal plans, progress, and macros." },
    signupDesc: { vi: "Bắt đầu track dinh dưỡng kiểu super easy.", en: "Start tracking your nutrition - super easy." },
    email: { vi: "Email", en: "Email" },
    password: { vi: "Mật khẩu", en: "Password" },
    submitLogin: { vi: "Đăng nhập", en: "Log in" },
    submitSignup: { vi: "Đăng ký", en: "Sign up" },
    wait: { vi: "Đang xử lý... ⏳", en: "Processing... ⏳" },
    needAccount: { vi: "Chưa có acc? Đăng ký ngay", en: "No account yet? Sign up" },
    haveAccount: { vi: "Có acc rồi? Đăng nhập", en: "Already in? Log in" },
    confirmEmail: { vi: "Check email để confirm tài khoản nha 📧", en: "Check your inbox to confirm your account 📧" },
    authMissing: {
      vi: "Thiết lập NEXT_PUBLIC_SUPABASE_URL và NEXT_PUBLIC_SUPABASE_ANON_KEY để bật xác thực.",
      en: "Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY to enable auth."
    },
    errorPrefix: { vi: "Lỗi", en: "Error" },
    loginRedirect: { vi: "Sau khi đăng nhập, bạn sẽ được chuyển về bảng điều khiển.", en: "After login, you will be redirected to the dashboard." }
  },
  workout: {
    plannerEyebrow: { vi: "Workout planner", en: "Workout planner" },
    plannerTitle: { vi: "Xây dựng lịch tập hằng tuần", en: "Build a weekly training split" },
    plannerDesc: { vi: "Planner chọn split và danh sách bài tập dựa trên mục tiêu, lịch và thiết bị của bạn.", en: "The planner picks a split and exercise list based on your goal, schedule, and equipment." },
    goalLabel: { vi: "Mục tiêu", en: "Goal" },
    experienceLabel: { vi: "Kinh nghiệm", en: "Experience level" },
    daysLabel: { vi: "Ngày / tuần", en: "Days per week" },
    sessionMinutesLabel: { vi: "Thời gian buổi (phút)", en: "Session length (minutes)" },
    equipmentLabel: { vi: "Thiết bị", en: "Equipment" },
    seedLabel: { vi: "Seed (tuỳ chọn)", en: "Seed (optional)" },
    seedPlaceholder: { vi: "Dùng để lặp lại plan cũ", en: "Use to repeat a plan" },
    buildPlan: { vi: "Sinh giáo án", en: "Build workout plan" },
    building: { vi: "Đang xây dựng...", en: "Building..." },
    createCustom: { vi: "Tạo plan tuỳ chỉnh", en: "Create custom plan" },
    editPlan: { vi: "Chỉnh sửa", en: "Edit plan" },
    customizePlan: { vi: "Tuỳ chỉnh", en: "Customize plan" },
    done: { vi: "Xong", en: "Done" },
    savePlan: { vi: "Lưu plan", en: "Save plan" },
    saving: { vi: "Đang lưu...", en: "Saving..." },
    viewHistory: { vi: "Xem lịch sử", en: "View history" },
    loadingHistory: { vi: "Đang tải...", en: "Loading..." },
    historyLatest: { vi: "Phiên bản gần đây", en: "Latest versions" },
    split: { vi: "Split", en: "Split" },
    sessions: { vi: "Buổi / tuần", en: "Sessions / week" },
    exercises: { vi: "Bài tập", en: "Exercises" },
    sessionLength: { vi: "Thời lượng buổi", en: "Session length" },
    daysSidebar: { vi: "Ngày tập", en: "Workout days" },
    daysSidebarHint: { vi: "Chọn từng day để xem bài tập chi tiết.", en: "Select a day to view exercises in detail." },
    addDay: { vi: "Thêm ngày", en: "Add day" },
    removeDay: { vi: "Xoá", en: "Remove" },
    exercisesSection: { vi: "Bài tập trong ngày này", en: "Exercises in this day" },
    exercisesSectionHint: { vi: "Hiển thị rõ từng bài tập và thông số.", en: "Detailed view of each exercise and parameters." },
    addExercise: { vi: "Thêm bài tập", en: "Add exercise" },
    viewProgress: { vi: "Xem tiến độ", en: "View progress" },
    saveSet: { vi: "Lưu set", en: "Save set" },
    setLabel: { vi: "Set", en: "Set" },
    repsLabel: { vi: "Reps", en: "Reps" },
    weightLabel: { vi: "Tạ (kg)", en: "Weight (kg)" },
    restLabel: { vi: "Nghỉ", en: "Rest" },
    exerciseNamePlaceholder: { vi: "Tên bài tập", en: "Exercise name" },
    dayNamePlaceholder: { vi: "Tên ngày", en: "Day name" },
    progressTitle: { vi: "Tiến độ bài tập", en: "Progress for" },
    progressHint: { vi: "Hiển thị mức tạ cao nhất theo ngày tập.", en: "Showing your top weight per training day." },
    logSetsPrompt: { vi: "Log set để xem biểu đồ tiến độ.", en: "Log sets for this exercise to see progress." },
    signInToSave: { vi: "Đăng nhập để lưu workout log.", en: "Sign in to save workout logs." },
    signInProgress: { vi: "Đăng nhập để xem tiến độ workout.", en: "Sign in to view workout progress." },
    selectDay: { vi: "Chọn một ngày tập để xem bài tập.", en: "Select a workout day to view exercises." },
    newExercise: { vi: "Bài tập mới", en: "New exercise" },
    editExerciseHint: { vi: "Chỉnh sửa chi tiết bài tập này.", en: "Edit details for this exercise." },
    historyError: { vi: "Không thể tải lịch sử plan.", en: "Unable to load plan history." },
    buildError: { vi: "Không thể sinh giáo án.", en: "Unable to build workout plan." },
    saveError: { vi: "Không thể lưu plan.", en: "Unable to save workout plan." },
    logSetError: { vi: "Không thể lưu log tập.", en: "Unable to save workout log." },
    progressError: { vi: "Không thể tải tiến độ bài tập.", en: "Unable to load workout progress." },
    signInRequired: { vi: "Cần đăng nhập", en: "Sign in required" },
    myPlan: { vi: "Plan của tôi", en: "My plan" },
    restAlmostDone: { vi: "Sắp hết!", en: "Almost done!" },
    restPause: { vi: "Tạm dừng", en: "Pause" },
    restResume: { vi: "Tiếp tục", en: "Resume" },
    restSkip: { vi: "Bỏ qua", en: "Skip" },
    lastSet: { vi: "Giống set trước", en: "Like last set" },
    save: { vi: "Lưu", en: "Save" },
    cancel: { vi: "Huỷ", en: "Cancel" },
    edit: { vi: "Sửa", en: "Edit" },
    delete: { vi: "Xoá", en: "Delete" },
    sessionActive: { vi: "Buổi tập đang diễn ra", en: "Session in progress" },
    sessionInactive: { vi: "Chưa bắt đầu", en: "Not started" },
    sessionHint: { vi: "Bắt đầu buổi tập để theo dõi thời lượng.", en: "Start a session to track duration." },
    startSession: { vi: "Bắt đầu buổi tập", en: "Start session" },
    finishSession: { vi: "Kết thúc buổi tập", en: "Finish session" },
    volumeTitle: { vi: "Khối lượng tập theo nhóm cơ", en: "Volume by muscle group" },
    streak: { vi: "Streak", en: "Streak" }
  },
  progress: {
    title: { vi: "Theo dõi tiến độ", en: "Progress tracking" },
    subtitle: { vi: "Thêm cân nặng và xem xu hướng", en: "Add weight and review the trend" },
    currentWeight: { vi: "Cân nặng hiện tại", en: "Current weight" },
    weightLabel: { vi: "Cân nặng (kg)", en: "Weight (kg)" },
    addEntry: { vi: "Thêm dữ liệu", en: "Add entry" },
    saving: { vi: "Đang lưu...", en: "Saving..." },
    entries: { vi: "Số dữ liệu", en: "Entries" },
    change: { vi: "Thay đổi", en: "Change" },
    trend: { vi: "Xu hướng", en: "Trend" },
    weightTrend: { vi: "Biểu đồ cân nặng", en: "Weight trend" },
    loading: { vi: "Đang tải tiến độ...", en: "Loading progress..." },
    signInLoad: { vi: "Đăng nhập để tải và lưu dữ liệu tiến độ.", en: "Sign in to load and save progress entries." },
    addTwo: { vi: "Thêm ít nhất hai lần nhập để xem biểu đồ.", en: "Add at least two entries to see the chart." },
    chartNote: { vi: "Dữ liệu tiến độ được hiển thị theo thời gian.", en: "Your progress entries plotted over time." },
    synced: { vi: "Đã đồng bộ", en: "Synced" },
    signInRequired: { vi: "Cần đăng nhập", en: "Sign in required" },
    saveError: { vi: "Không thể lưu dữ liệu tiến độ.", en: "Unable to save progress entry." },
    loadError: { vi: "Không thể tải dữ liệu tiến độ.", en: "Unable to load progress entries." }
  }
} as const;

export type Strings = typeof strings;
export type StringKey = keyof Strings;
export function t<T extends Record<Language, string>>(value: T, language: Language) {
  return value[language];
}
